server {
    listen 80;
    server_name localhost;

    root /var/www/html/frontend/dist;          # Vue SPA — основной root
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;      # SPA fallback
    }

    location /api/ {
        alias /var/www/html/backend/public/;   # PHP точка входа
        try_files $uri $uri/ /api/index.php?$query_string;

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass create:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $request_filename;
            # fastcgi_param PATH_INFO $fastcgi_path_info;
        }
    }

    # Опционально: deny скрытые файлы
    location ~ /\. {
        deny all;
    }
}